name: Kubernetes cleaner for staging

on:
  push:
    branches:
      - main
    paths:
      - 'maintain/kube_pod_cleaner/**'

env:
  SRC_FOLDER: ./maintain/kube_pod_cleaner/

jobs:
  docker_build_and_push:
    runs-on: ubuntu-latest
    name: Build

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Packages
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_CONTAINER_REGISTRY_USER }}
          password: ${{ secrets.GHCR_TOKEN }}
        
      - uses: docker/build-push-action@v2
        with:
          context: ${{ env.SRC_FOLDER}}
          file: ${{ env.SRC_FOLDER}}Dockerfile
          push: true
          tags: |
            ghcr.io/city-of-helsinki/${{ github.event.repository.name }}/kube_pod_cleaner:latest
            ghcr.io/city-of-helsinki/${{ github.event.repository.name }}/kube_pod_cleaner:dev

  staging:
    runs-on: ubuntu-latest
    needs: docker_build_and_push
    name: Staging

    # allow only one deployment at a time
    concurrency: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v2

      - name: Deploy Order Expiration Cronjob
        uses: City-of-Helsinki/setup-cronjob-action@main
        with:
          image_repository: ghcr.io/city-of-helsinki/${{ github.event.repository.name }}/kube_pod_cleaner
          kubeconfig_raw: ${{ secrets.KUBECONFIG_RAW_STAGING}}
          target_namespace: ${{ secrets.K8S_NAMESPACE_STAGING}}
          name: pod-cleaner
